services:
  - type: web
    name: groq-insurance-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: TEAM_TOKEN
        sync: false
    autoDeploy: true
