services:
  - type: web
    name: ai-insure1
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: TEAM_TOKEN
        sync: false
    autoDeploy: true
